// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: serversHandler.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LobbyService.Grpc {

  /// <summary>Holder for reflection information generated from serversHandler.proto</summary>
  public static partial class ServersHandlerReflection {

    #region Descriptor
    /// <summary>File descriptor for serversHandler.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServersHandlerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzZXJ2ZXJzSGFuZGxlci5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5",
            "LnByb3RvIn0KFFBvc3RMb2JieUluZm9SZXF1ZXN0EhkKEXB1YmxpY19pcF9h",
            "ZGRyZXNzGAEgASgJEgwKBHBvcnQYAiABKAUSEQoJbWF4X3NlYXRzGAMgASgF",
            "EhUKDXBsYXllcnNfY291bnQYBCABKAUSEgoKbG9iYnlfbmFtZRgFIAEoCTKN",
            "AQoOU2VydmVyc0hhbmRsZXISPgoNUG9zdExvYmJ5SW5mbxIVLlBvc3RMb2Ji",
            "eUluZm9SZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EjsKCURyb3BM",
            "b2JieRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1",
            "Zi5FbXB0eUIUqgIRTG9iYnlTZXJ2aWNlLkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LobbyService.Grpc.PostLobbyInfoRequest), global::LobbyService.Grpc.PostLobbyInfoRequest.Parser, new[]{ "PublicIpAddress", "Port", "MaxSeats", "PlayersCount", "LobbyName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PostLobbyInfoRequest : pb::IMessage<PostLobbyInfoRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PostLobbyInfoRequest> _parser = new pb::MessageParser<PostLobbyInfoRequest>(() => new PostLobbyInfoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PostLobbyInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LobbyService.Grpc.ServersHandlerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostLobbyInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostLobbyInfoRequest(PostLobbyInfoRequest other) : this() {
      publicIpAddress_ = other.publicIpAddress_;
      port_ = other.port_;
      maxSeats_ = other.maxSeats_;
      playersCount_ = other.playersCount_;
      lobbyName_ = other.lobbyName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostLobbyInfoRequest Clone() {
      return new PostLobbyInfoRequest(this);
    }

    /// <summary>Field number for the "public_ip_address" field.</summary>
    public const int PublicIpAddressFieldNumber = 1;
    private string publicIpAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublicIpAddress {
      get { return publicIpAddress_; }
      set {
        publicIpAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 2;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "max_seats" field.</summary>
    public const int MaxSeatsFieldNumber = 3;
    private int maxSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxSeats {
      get { return maxSeats_; }
      set {
        maxSeats_ = value;
      }
    }

    /// <summary>Field number for the "players_count" field.</summary>
    public const int PlayersCountFieldNumber = 4;
    private int playersCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayersCount {
      get { return playersCount_; }
      set {
        playersCount_ = value;
      }
    }

    /// <summary>Field number for the "lobby_name" field.</summary>
    public const int LobbyNameFieldNumber = 5;
    private string lobbyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LobbyName {
      get { return lobbyName_; }
      set {
        lobbyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PostLobbyInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PostLobbyInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PublicIpAddress != other.PublicIpAddress) return false;
      if (Port != other.Port) return false;
      if (MaxSeats != other.MaxSeats) return false;
      if (PlayersCount != other.PlayersCount) return false;
      if (LobbyName != other.LobbyName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PublicIpAddress.Length != 0) hash ^= PublicIpAddress.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (MaxSeats != 0) hash ^= MaxSeats.GetHashCode();
      if (PlayersCount != 0) hash ^= PlayersCount.GetHashCode();
      if (LobbyName.Length != 0) hash ^= LobbyName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PublicIpAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PublicIpAddress);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Port);
      }
      if (MaxSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxSeats);
      }
      if (PlayersCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayersCount);
      }
      if (LobbyName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LobbyName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PublicIpAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PublicIpAddress);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Port);
      }
      if (MaxSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxSeats);
      }
      if (PlayersCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayersCount);
      }
      if (LobbyName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LobbyName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PublicIpAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicIpAddress);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      if (MaxSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxSeats);
      }
      if (PlayersCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayersCount);
      }
      if (LobbyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LobbyName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PostLobbyInfoRequest other) {
      if (other == null) {
        return;
      }
      if (other.PublicIpAddress.Length != 0) {
        PublicIpAddress = other.PublicIpAddress;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.MaxSeats != 0) {
        MaxSeats = other.MaxSeats;
      }
      if (other.PlayersCount != 0) {
        PlayersCount = other.PlayersCount;
      }
      if (other.LobbyName.Length != 0) {
        LobbyName = other.LobbyName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PublicIpAddress = input.ReadString();
            break;
          }
          case 16: {
            Port = input.ReadInt32();
            break;
          }
          case 24: {
            MaxSeats = input.ReadInt32();
            break;
          }
          case 32: {
            PlayersCount = input.ReadInt32();
            break;
          }
          case 42: {
            LobbyName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PublicIpAddress = input.ReadString();
            break;
          }
          case 16: {
            Port = input.ReadInt32();
            break;
          }
          case 24: {
            MaxSeats = input.ReadInt32();
            break;
          }
          case 32: {
            PlayersCount = input.ReadInt32();
            break;
          }
          case 42: {
            LobbyName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
